# Introduction

Working with data and models, using to create valuable and impactful
information is a complex task. It requires a combination of technical
skills, domain knowledge, and an understanding of the broader context in
which the data and models are used. 

The effictive and responsible use of data and models is crucial for
researchers. It must me clear how resulta are obtained, what the
limitations are, and how they can be reproduced. This is where the
Fair Software for Research (FS4R) book comes in. The knowlesge of this
book is based on standing practices in data science and data
software engineering,

This book is written to help you to
apply these standards to your work in a hands on way. We will not explain
each standard in detail but only briefly mention or link them where relevant. What
we will do is to show you best practices about data science and data
engineering that will help you to improve your research and make your
work reproducible, transparent, reusable and reliable.

This book is writen for data scientist, data modellers, data analysts,
data managers and anybody else working with data. The book is
collaborative effort and anybody is welcome to contribute.

::: {.callout-note}
TODO: explain how to contribute
:::

## How to use this book?

While this is a book, it is not meant to be read from cover to cover. It
a is a collection of guidances and recipes that you can use when you are
doing your research. You can read the book in any order or just pick
the chapters that are relevant to you. Each chapter is self contained
and can be read independently. However, the order of the chapters is
logical for somebody who is new to data science or the way of working
with data and models.



